/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "iscswsczvtjwwmwrlnxz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzY3N3c2N6dnRqd3dtd3Jsbnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5Mzc4MjQsImV4cCI6MjA4NTUxMzgyNH0.VWz-G1F-psTlBPcxIuTV1r-9hWk7HnVp0bEFNajPQQA"